//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ica.SalesOrders.Web.SchedeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Scheda", Namespace="http://schemas.datacontract.org/2004/07/WSSchede")]
    [System.SerializableAttribute()]
    public partial class Scheda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinguaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codice {
            get {
                return this.CodiceField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceField, value) != true)) {
                    this.CodiceField = value;
                    this.RaisePropertyChanged("Codice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemID {
            get {
                return this.ItemIDField;
            }
            set {
                if ((this.ItemIDField.Equals(value) != true)) {
                    this.ItemIDField = value;
                    this.RaisePropertyChanged("ItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lingua {
            get {
                return this.LinguaField;
            }
            set {
                if ((object.ReferenceEquals(this.LinguaField, value) != true)) {
                    this.LinguaField = value;
                    this.RaisePropertyChanged("Lingua");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SchedeService.ISchede")]
    public interface ISchede {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchede/DoWork", ReplyAction="http://tempuri.org/ISchede/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchede/DoWork", ReplyAction="http://tempuri.org/ISchede/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchede/GetSchede", ReplyAction="http://tempuri.org/ISchede/GetSchedeResponse")]
        Ica.SalesOrders.Web.SchedeService.Scheda[] GetSchede(string Codice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchede/GetSchede", ReplyAction="http://tempuri.org/ISchede/GetSchedeResponse")]
        System.Threading.Tasks.Task<Ica.SalesOrders.Web.SchedeService.Scheda[]> GetSchedeAsync(string Codice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchede/GetScheda", ReplyAction="http://tempuri.org/ISchede/GetSchedaResponse")]
        System.IO.Stream GetScheda(int ItemID, string Tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchede/GetScheda", ReplyAction="http://tempuri.org/ISchede/GetSchedaResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetSchedaAsync(int ItemID, string Tipo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISchedeChannel : Ica.SalesOrders.Web.SchedeService.ISchede, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SchedeClient : System.ServiceModel.ClientBase<Ica.SalesOrders.Web.SchedeService.ISchede>, Ica.SalesOrders.Web.SchedeService.ISchede {
        
        public SchedeClient() {
        }
        
        public SchedeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SchedeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchedeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchedeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public Ica.SalesOrders.Web.SchedeService.Scheda[] GetSchede(string Codice) {
            return base.Channel.GetSchede(Codice);
        }
        
        public System.Threading.Tasks.Task<Ica.SalesOrders.Web.SchedeService.Scheda[]> GetSchedeAsync(string Codice) {
            return base.Channel.GetSchedeAsync(Codice);
        }
        
        public System.IO.Stream GetScheda(int ItemID, string Tipo) {
            return base.Channel.GetScheda(ItemID, Tipo);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetSchedaAsync(int ItemID, string Tipo) {
            return base.Channel.GetSchedaAsync(ItemID, Tipo);
        }
    }
}
